[project]
name = "py-resume"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cyclopts>=4.2.5",
    "jinja2>=3.1.6",
    "playwright>=1.56.0",
    "pydantic>=2.12.4",
    "jinja-markdown>=1.210911",
]
